export const NAV_ITEMS: { href: string; label: string }[] = [
  { href: "/", label: "Dashboard" },
  { href: "/search", label: "Search" },
  { href: "/watchlist", label: "Watchlist" },
  { href: "/posCalculator", label: "PositionCalculator" },
];

export const MARKET_OVERVIEW_WIDGET_CONFIG = {
  allow_symbol_change: true,
  calendar: false,
  details: false,
  hide_side_toolbar: true,
  hide_top_toolbar: false,
  hide_legend: false,
  hide_volume: false,
  hotlist: false,
  interval: "D",
  locale: "en",
  save_image: true,
  style: "1",
  symbol: "NASDAQ:AAPL",
  theme: "light",
  timezone: "Etc/UTC",
  backgroundColor: "#ffffff",
  gridColor: "rgba(46, 46, 46, 0.06)",
  watchlist: [],
  withdateranges: false,
  compareSymbols: [],
  studies: [],
  autosize: true,
};
